name: Linting

on: pull_request

jobs:
  Prettier:
    name: prettier-ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run lint:prettier:check
  ESlint:
    name: eslint-ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run lint:eslint:check
